export default {
    sn: {},
    asset_status: {},
    location: { sorter: false, export: false },
    group: { sorter: false },
    hostname: {},
    ip: {},
    ip_mac: {},
    bmc_address: {},
    manage_nic_mac: {},
    usage_person: {},
    owner_person: {},
    collector: {},
    other_ip: { title: '其它 IP' },
    site: {},
    asset_no: {},
    asset_type: {},
    os: {},
    bootos_version: {},
    vendor: {},
    model: {},
    cpu_model: {},
    cpu_num: {},
    cpu_num_core: {},
    memory: {},
    mem_usage: {},
    disk: {},
    ssd: {},
    raid: {},
    nic: {},
    encryption_dog: {},
    arrive_time: {},
    launched_time: {},
    check_time: {},
    order_no: {},
    contract_no: {},
    warranty_period: {},
    warranty_period_end: {},
    power: {},
    department_id: {},
    domain: {},
    supplier_id: {},
    role: {},
    kernel_version: {},
    os_disk: {},
    idc_id: {},
    floor_id: {},
    room_id: {},
    rack_id: {},
    col_id: {},
    height: {},
    position: {},
    tag: { sorter: false },
    uuid: {},
    memo: {},
    other_sn: {},
    update_time: {},
    create_time: {},
}
